---
    - name: firewalld stop
      service: name=firewalld state=stopped enabled=no

    - name: zabbix-agent start
      service: name=zabbix-agent state=started enabled=yes

    - name: chronyd stop
      service: name=chronyd state=stopped enabled=no

    - name: ntpd start
      service: name=ntpd state=started enabled=yes

    - name: ntpd restart
      service: name=ntpd state=restarted

