- hosts: centos
  user: root
  tasks: 
  - name: Install EPEL repo
    yum:
      name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm
      state: present
  - name: Install remi repo
    yum:
      name: http://rpms.famillecollet.com/enterprise/remi-release-{{ ansible_distribution_major_version }}.rpm
      state: present
  - name: Import remi GPG key
    rpm_key:
      key: http://rpms.remirepo.net/RPM-GPG-KEY-remi
      state: present
  - name: Install RPM with ocs-invetory
    yum: 
      name: https://rpm.ocsinventory-ng.org/ocsinventory-release-latest.el7.ocs.noarch.rpm
  - name: Import OCS GPG key
    rpm_key:
      key: /etc/pki/rpm-gpg/RPM-GPG-KEY-ocs
  - name: Install Agent
    yum: 
      name: ocsinventory-agent
      state: present
  - name: Copy CFG of ocsinventory-agent
    copy: src=ocsinventory-agent.cfg dest=/etc/ocsinventory/ owner=root group=root
  - name: Send Info from Agent to Server	
    command: /usr/sbin/ocsinventory-agent
